# DEV
quarkus.http.port=8081

# to make swagger ui look cool
quarkus.swagger-ui.theme=original
quarkus.log.console.json=false
quarkus.console.color=true

quarkus.mongodb.database=Tinyx
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://admin:admin@localhost:27017/?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD}


tinyx.user-timeline.collection=UserTimeline
tinyx.redis-stream.trim.every=10m
tinyx.redis-stream.claim.every=5s
tinyx.rest-client.srvc-post.host=http://localhost:8081
quarkus.rest-client.tinyx.rest-client.srvc-post.host.url=http://localhost:8081
