---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-social
  labels:
    app: tinyx
    module: srvc-social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyx
      module: srvc-social
  template:
    metadata:
      labels:
        app: tinyx
        module: srvc-social
    spec:
      imagePullSecrets:
        - name: tinyx-pull-secret
      containers:
        - name: srvc-social
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-14/srvc-social
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-env
            - configMapRef:
                name: social-env
            - configMapRef:
                name: srvc-social-env
            - secretRef:
                name: tinyx-mongodb-credentials
          env:
            - name: HTTP_PORT
              value: "8080"
          resources:
            limits:
              cpu: "500m" # 0.25 cpu      #Arbitrary values to eventually customize or remove completely
              memory: "256Mi" # 128 Mega  #(These were instored to suppress an IDE warning)
