image: maven:latest

stages:
  - lint
  - build-common
  - compile
  - test

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

lint:
  stage: lint
  parallel:
    matrix:
      - SERVICE: ["repo-post", "repo-social", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS spotless:check

build-common:
  stage: build-common
  script:
    - cd tinyX
    - mvn -pl common $MAVEN_CLI_OPTS clean install -DskipTests
  needs:
    - lint
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
    expire_in: 1h

compile:
  stage: compile
  parallel:
    matrix:
      - SERVICE: ["repo-post", "repo-social", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  needs:
    - build-common
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS compile -am
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
    expire_in: 1h

test:
  stage: test
  parallel:
    matrix:
      - SERVICE: ["repo-post", "repo-social", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  needs:
    - compile
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS test -am
