image: maven:latest

stages:
  - deploy
  - lint
  - build-common
  - compile
  - test

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_CONFIG: "/kaniko/.docker/"
  VERSION: "${CI_COMMIT_TAG#build-}"

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]  # empêche GitLab de lancer `sh`
  parallel:
    matrix:
      - SERVICE: ["srvc-user"]
  script:
    - mkdir -p /kaniko/.docker
    - >
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}"
      > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context "tinyX"
      --dockerfile "tinyX/$SERVICE/Dockerfile"
      --destination "$CI_REGISTRY_IMAGE/$SERVICE:$VERSION"

lint:
  stage: lint
  parallel:
    matrix:
      - SERVICE: ["common", "repo-search", "repo-media", "repo-post", "repo-social", "repo-home-timeline", "repo-user-timeline", "srvc-media", "srvc-user", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS spotless:check

build-common:
  stage: build-common
  script:
    - cd tinyX
    - mvn -pl common $MAVEN_CLI_OPTS clean install -DskipTests
  needs:
    - lint
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
    expire_in: 1h

compile:
  stage: compile
  parallel:
    matrix:
      - SERVICE: ["repo-search", "repo-media", "repo-post", "repo-social", "repo-home-timeline", "repo-user-timeline", "srvc-media", "srvc-user", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  needs:
    - build-common
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS compile -am
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
    expire_in: 1h

test:
  stage: test
  services:
    - name: mongo:latest
      alias: mongo
    - name: redis:alpine
      alias: redis
    - name: neo4j:3.5
      alias: neo4j
  variables:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: admin
    MONGO_INITDB_DATABASE: Tinyx
    NEO4J_AUTH: none
    MONGODB_CONNECTION_STRING: "mongodb://admin:admin@mongo:27017/?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD"
    REDIS_CONNECTION_STRING: "redis://redis:6379"
    NEO4J_CONNECTION_STRING: "bolt://neo4j:7687"
  parallel:
    matrix:
      - SERVICE: ["repo-search", "repo-media", "repo-post", "repo-social", "repo-home-timeline", "repo-user-timeline", "srvc-media", "srvc-user", "srvc-post", "srvc-social", "srvc-home-timeline", "srvc-search", "srvc-user-timeline"]
  needs:
    - compile
  script:
    - cd tinyX
    - mvn -pl $SERVICE $MAVEN_CLI_OPTS test -am
