# DEV
quarkus.http.port=8090
# to make swagger ui look cool

quarkus.swagger-ui.theme=original
quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.mongodb.database=Tinyx
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://admin:admin@localhost:27017/?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD}
