quarkus.http.port=${HTTP_PORT:8084}


quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.elasticsearch.hosts=${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}

quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}

tinyx.elasticsearch.index=${ELASTIC_INDEX:posts}
post-client/mp-rest/url=http://${REST_HOST:localhost}:${REST_PORT:8085}/