# DEV
quarkus.http.port=${HTTP_PORT:8085}

quarkus.log.console.json=false
quarkus.console.color=true

quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:${MONGODB_DATABASE:mongodb}://${MONGODB_USER:admin}:${MONGODB_PASSWD:admin}@${MONGODB_HOST:localhost}:27017/?authSource=${MONGODB_PASSWD}&retryWrites=true&w=majority&uuidRepresentation=STANDARD}
quarkus.mongodb.database=${MONGODB_DATABASE:Tinyx}
