---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "ZXRpZW5uZS5zZW5pZ291dDpYcVBSa0J5QWtROUx6YlRzWjU5UQ=="
          }
      }
    }
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-mongodb-credentials
data:
  MONGODB_USER: YWRtaW4= #admin
  MONGODB_PASSWORD: YWRtaW4= #admin
