quarkus.http.port=${HTTP_PORT:8081}

quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.mongodb.database=${MONGODB_DATABASE:Tinyx}
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://${MONGODB_USER:admin}:${MONGODB_PASSWD:admin}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/?authSource=${MONGODB_DATABASE:Tinyx}&retryWrites=true&w=majority&uuidRepresentation=STANDARD}

post-client/mp-rest/url=http://${POST_REST_HOST:localhost}:${POST_REST_PORT:8085}
