---
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: srvc-media-env
    literals:
      - TRIM_INTERVAL="10m"
      - CLAIM_INTERVAL="5s"
