quarkus.http.port=${HTTP_PORT:8092}


quarkus.elasticsearch.hosts=${ELASTIC_CONNECTION_STRING:${ELASTIC_HOST:localhost}:${ELASTIC_PORT:9200}}

quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}

tinyx.elasticsearch.index=${ELASTIC_INDEX:posts}
tinyx.redis-stream.trim.every=${TRIM_INTERVAL:10m}
tinyx.redis-stream.claim.every=${CLAIM_INTERVAL:5s}
