quarkus.http.port=8085

# to make swagger ui look cool
quarkus.swagger-ui.theme=original
quarkus.elasticsearch.hosts=${ELASTIC_CONNECTION_STRING:localhost:9200}

quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}

tinyx.elasticsearch.index=posts
tinyx.redis-stream.trim.every=10m
tinyx.redis-stream.claim.every=5s
