quarkus.http.port=${HTTP_PORT:8083}

quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.neo4j.uri = ${NEO4J_CONNECTION_STRING:bolt://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}}
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}}

post-client/mp-rest/url=http://${POST_REST_HOST:localhost}:${POST_REST_PORT:8085}/
user-client/mp-rest/url=http://${USER_REST_HOST:localhost}:${USER_REST_PORT:8086}
