# DEV
quarkus.http.port=8081

quarkus.log.console.json=false
quarkus.console.color=true

quarkus.neo4j.uri = bolt://localhost:7687
quarkus.elasticsearch.hosts = localhost:9200

quarkus.mongodb.database=Tinyx
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://admin:admin@localhost:27017/?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD}

tinyx.redis-stream.trim.every=10m
tinyx.redis-stream.claim.every=5s
