# DEV
quarkus.http.port=8090
# to make swagger ui look cool

quarkus.swagger-ui.theme=original

quarkus.neo4j.uri = ${NEO4J_CONNECTION_STRING:bolt://localhost:7687}
quarkus.console.color=true
quarkus.log.console.json=false
quarkus.console.enabled=false
quarkus.redis.hosts=${REDIS_CONNECTION_STRING:redis://localhost:6379}