# DEV
quarkus.http.port=8081
# to make swagger ui look cool

quarkus.swagger-ui.theme=original


quarkus.neo4j.uri = bolt://localhost:7687
quarkus.console.color=true
quarkus.log.console.json=false
quarkus.redis.hosts=redis://localhost:6379

