# DEV
quarkus.http.port=8088
# to make swagger ui look cool

quarkus.swagger-ui.theme=original
quarkus.log.console.json=false
quarkus.console.color=true
quarkus.console.enabled=false

quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://admin:admin@localhost:27017/?authSource=admin&retryWrites=true&w=majority&uuidRepresentation=STANDARD}
quarkus.mongodb.database=Tinyx
tinyx.mongo.media.bucket=Media

tinyx.redis-stream.trim.every=10m
tinyx.redis-stream.claim.every=5s

quarkus.http.limits.max-form-attribute-size=32M
