---
kind: Kustomization

resources:
  - deployment.yml

configMapGenerator:
  - name: repo-user-timeline-env
    literals:
      - TRIM_INTERVAL="10m"
      - CLAIM_INTERVAL="5s"
      - POST_REST_HOST="srvc-post-service.tinyx.svc.cluster.local"
      - POST_REST_PORT="8080"
